// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: fs.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FS_Upload_FullMethodName   = "/FS/Upload"
	FS_Download_FullMethodName = "/FS/Download"
	FS_Echo_FullMethodName     = "/FS/Echo"
	FS_Echo2_FullMethodName    = "/FS/Echo2"
)

// FSClient is the client API for FS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FSClient interface {
	Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, UploadResponse], error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error)
	Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoResponse, error)
	Echo2(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoResponse, error)
}

type fSClient struct {
	cc grpc.ClientConnInterface
}

func NewFSClient(cc grpc.ClientConnInterface) FSClient {
	return &fSClient{cc}
}

func (c *fSClient) Upload(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Chunk, UploadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FS_ServiceDesc.Streams[0], FS_Upload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Chunk, UploadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FS_UploadClient = grpc.ClientStreamingClient[Chunk, UploadResponse]

func (c *fSClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FS_ServiceDesc.Streams[1], FS_Download_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DownloadRequest, Chunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FS_DownloadClient = grpc.ServerStreamingClient[Chunk]

func (c *fSClient) Echo(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, FS_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fSClient) Echo2(ctx context.Context, in *EchoMessage, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, FS_Echo2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FSServer is the server API for FS service.
// All implementations must embed UnimplementedFSServer
// for forward compatibility.
type FSServer interface {
	Upload(grpc.ClientStreamingServer[Chunk, UploadResponse]) error
	Download(*DownloadRequest, grpc.ServerStreamingServer[Chunk]) error
	Echo(context.Context, *EchoMessage) (*EchoResponse, error)
	Echo2(context.Context, *EchoMessage) (*EchoResponse, error)
	mustEmbedUnimplementedFSServer()
}

// UnimplementedFSServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFSServer struct{}

func (UnimplementedFSServer) Upload(grpc.ClientStreamingServer[Chunk, UploadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Upload not implemented")
}
func (UnimplementedFSServer) Download(*DownloadRequest, grpc.ServerStreamingServer[Chunk]) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedFSServer) Echo(context.Context, *EchoMessage) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedFSServer) Echo2(context.Context, *EchoMessage) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo2 not implemented")
}
func (UnimplementedFSServer) mustEmbedUnimplementedFSServer() {}
func (UnimplementedFSServer) testEmbeddedByValue()            {}

// UnsafeFSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FSServer will
// result in compilation errors.
type UnsafeFSServer interface {
	mustEmbedUnimplementedFSServer()
}

func RegisterFSServer(s grpc.ServiceRegistrar, srv FSServer) {
	// If the following call pancis, it indicates UnimplementedFSServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FS_ServiceDesc, srv)
}

func _FS_Upload_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FSServer).Upload(&grpc.GenericServerStream[Chunk, UploadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FS_UploadServer = grpc.ClientStreamingServer[Chunk, UploadResponse]

func _FS_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(DownloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FSServer).Download(m, &grpc.GenericServerStream[DownloadRequest, Chunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FS_DownloadServer = grpc.ServerStreamingServer[Chunk]

func _FS_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FSServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FS_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FSServer).Echo(ctx, req.(*EchoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _FS_Echo2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FSServer).Echo2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FS_Echo2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FSServer).Echo2(ctx, req.(*EchoMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// FS_ServiceDesc is the grpc.ServiceDesc for FS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FS",
	HandlerType: (*FSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _FS_Echo_Handler,
		},
		{
			MethodName: "Echo2",
			Handler:    _FS_Echo2_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Upload",
			Handler:       _FS_Upload_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _FS_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "fs.proto",
}
